# Generated by Django 6.0.3 on 2026-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('punch_date', models.DateField(auto_now_add=True)),
                ('punched_at', models.DateTimeField(auto_now_add=True)),
                ('punch_type', models.CharField(choices=[('PUNCH_IN', 'Punch In'), ('PUNCH_OUT', 'Punch Out')], default='PUNCH_IN', max_length=20)),
                ('distance_from_last', models.FloatField(blank=True, help_text='Distance in km from last punch', null=True)),
                ('notes', models.TextField(blank=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-punched_at'],
            },
        ),
        migrations.CreateModel(
            name='TravelRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_latitude', models.FloatField()),
                ('from_longitude', models.FloatField()),
                ('to_latitude', models.FloatField()),
                ('to_longitude', models.FloatField()),
                ('distance_km', models.FloatField()),
                ('travel_time_minutes', models.IntegerField()),
                ('purpose', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(auto_now_add=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_distance', models.FloatField(default=0, help_text='Total distance in km')),
                ('stop_count', models.IntegerField(default=0, help_text='Number of locations visited')),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-session_date'],
            },
        ),
    ]
