# Generated by Django 6.0.3 on 2026-03-17 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepunch',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_punches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelsession',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='travelroute',
            name='travel_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='attendance.travelsession'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['employee', 'punch_date'], name='attendance__employe_a7cd1c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancepunch',
            index=models.Index(fields=['punch_date'], name='attendance__punch_d_fa53ed_idx'),
        ),
    ]
