# Generated by Django 6.0.3 on 2026-03-18 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancepunch_accuracy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correction_type', models.CharField(choices=[('ADD_PUNCH', 'Add Missing Punch'), ('EDIT_PUNCH', 'Edit Existing Punch'), ('DELETE_PUNCH', 'Delete Incorrect Punch')], default='ADD_PUNCH', max_length=20)),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('requested_latitude', models.FloatField(blank=True, null=True)),
                ('requested_longitude', models.FloatField(blank=True, null=True)),
                ('requested_punch_type', models.CharField(choices=[('PUNCH_IN', 'Punch In'), ('PUNCH_OUT', 'Punch Out')], default='PUNCH_IN', max_length=20)),
                ('reason', models.TextField(help_text='Reason for the correction request')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_correction_requests', to=settings.AUTH_USER_MODEL)),
                ('existing_punch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='attendance.attendancepunch')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_correction_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='attendance__employe_8ed3c1_idx'), models.Index(fields=['status', 'created_at'], name='attendance__status_515e98_idx')],
            },
        ),
    ]
