build:
  owner: mishra-naveen-dev
  repo: tas-backend
  branch: main
  pythonVersion: "3.14.3"
  buildCommand: pip install -r requirements.txt && python manage.py migrate --fake-initial && python manage.py create_test_users && python manage.py collectstatic --no-input && python manage.py seed_features
  outputDir: backend

services:
  - type: web
    name: tas-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --fake-initial && python manage.py create_test_users && python manage.py collectstatic --no-input && python manage.py seed_features
    startCommand: gunicorn traveling_allowance.wsgi:application --workers 2 --threads 4 --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromGroup: tas-database
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "tas-backend-8emb.onrender.com"