# Generated by Django 6.0.3 on 2026-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ALLOWANCE_APPROVED', 'Allowance Approved'), ('ALLOWANCE_REJECTED', 'Allowance Rejected'), ('ALLOWANCE_PENDING', 'Allowance Pending Review'), ('PUNCH_REMINDER', 'Punch Reminder'), ('LOAN_FOLLOW_UP', 'Loan Follow-up'), ('SYSTEM', 'System')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_id', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
