# Generated by Django 6.0.3 on 2026-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('PUNCH_IN', 'Punch In'), ('PUNCH_OUT', 'Punch Out'), ('ALLOWANCE_REQUEST', 'Allowance Request'), ('ALLOWANCE_APPROVE', 'Allowance Approve'), ('ALLOWANCE_REJECT', 'Allowance Reject'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('OTHER', 'Other')], max_length=50)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=255)),
                ('old_values', models.TextField(blank=True, help_text='JSON of previous values', null=True)),
                ('new_values', models.TextField(blank=True, help_text='JSON of new values', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
