# Generated by Django 6.0.3 on 2026-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_type', models.CharField(choices=[('ALLOWANCE', 'Allowance Request'), ('LEAVE', 'Leave Request'), ('EXPENSE', 'Expense Claim')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('approval_levels', models.IntegerField(default=2)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
