# Generated by Django 6.0.3 on 2026-03-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=250)),
                ('customer_phone', models.CharField(blank=True, max_length=15)),
                ('customer_location', models.CharField(blank=True, max_length=500)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DEFAULT', 'Default'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('visit_time', models.TimeField()),
                ('visit_type', models.CharField(choices=[('COLLECTION', 'Collection'), ('FOLLOW_UP', 'Follow Up'), ('DISBURSEMENT', 'Disbursement'), ('DOCUMENT_COLLECTION', 'Document Collection'), ('OTHER', 'Other')], max_length=50)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('distance_traveled', models.FloatField(blank=True, help_text='Distance in km', null=True)),
                ('purpose', models.TextField()),
                ('observations', models.TextField(blank=True)),
                ('outcome', models.CharField(blank=True, max_length=255)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
