# Generated by Django 6.0.3 on 2026-03-17 15:57

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanvisit',
            options={'ordering': ['-visit_datetime']},
        ),
        migrations.AddField(
            model_name='loanvisit',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='loanvisit',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Transaction amount in ₹', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanvisit',
            name='description',
            field=models.TextField(blank=True, help_text='Additional notes or description'),
        ),
        migrations.AddField(
            model_name='loanvisit',
            name='location',
            field=models.CharField(blank=True, help_text='Human-readable location', max_length=500),
        ),
        migrations.AddField(
            model_name='loanvisit',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('RECOVERY', 'Loan Recovery'), ('DISBURSEMENT', 'Loan Disbursement'), ('PAYMENT', 'Payment'), ('OTHER', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanvisit',
            name='visit_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Automatic timestamp'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='loanvisit',
            index=models.Index(fields=['visited_by', 'visit_date'], name='loans_loanv_visited_b8c815_idx'),
        ),
        migrations.AddIndex(
            model_name='loanvisit',
            index=models.Index(fields=['visit_datetime'], name='loans_loanv_visit_d_a61969_idx'),
        ),
    ]
