# Generated by Django 5.2.11 on 2026-03-02 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PunchIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('punched_at', models.DateTimeField(auto_now_add=True)),
                ('punched_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-punched_at'],
                'indexes': [models.Index(fields=['user', 'punched_date'], name='attendance__user_id_52df33_idx')],
            },
        ),
    ]
