# Generated by Django 5.2.11 on 2026-03-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punchin',
            name='distance_from_last',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8),
        ),
    ]
