# Generated by Django 6.0.3 on 2026-03-17 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allowance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allowanceapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowancerequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_allowances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowancerequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='allowancedocument',
            name='allowance_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='allowance.allowancerequest'),
        ),
        migrations.AddField(
            model_name='allowanceapproval',
            name='allowance_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='allowance.allowancerequest'),
        ),
        migrations.AddIndex(
            model_name='allowancerequest',
            index=models.Index(fields=['employee', 'travel_date'], name='allowance_a_employe_9ae022_idx'),
        ),
        migrations.AddIndex(
            model_name='allowancerequest',
            index=models.Index(fields=['status'], name='allowance_a_status_866fdc_idx'),
        ),
    ]
