# Generated by Django 6.0.3 on 2026-03-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allowance', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_daily', models.DecimalField(decimal_places=2, default=250, max_digits=10)),
                ('per_km', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
