# Generated by Django 6.0.3 on 2026-03-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allowance', '0003_allowanceconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowanceconfig',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='allowanceconfig',
            name='fixed_daily',
        ),
        migrations.RemoveField(
            model_name='allowancerequest',
            name='distance_allowance',
        ),
        migrations.RemoveField(
            model_name='allowancerequest',
            name='fixed_allowance',
        ),
        migrations.RemoveField(
            model_name='allowancerequest',
            name='misc_amount',
        ),
        migrations.RemoveField(
            model_name='allowancerequest',
            name='total_amount',
        ),
    ]
