# Generated by Django 6.0.3 on 2026-03-28 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_user_options_user_created_by_user_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
